### ISSUE TITLE
Skopos ground stations have no atmosphere/pointing noise applied

### ISSUE THREAD

**Issue by Capkirk123** [mockingbirdnest/Skopos#15]
Partner issue to https://github.com/KSP-RO/RealAntennas/issues/38, as resolving it may demand changes from both mods

As shown in this screenshot of the connection debugger, no atmospheric noise is applied to receiving ground station, even with the antenna pointing a mere 0.9 degrees above the horizon.

Possibly related to https://github.com/KSP-RO/RealAntennas/issues/14, which also appears to stem from RealAntennas not quite realizing Skopos ground stations are ground stations and treating them as vessel antennas instead (vessel antennas do not have atmospheric noise calculations applied)

**Comment by eggrobin** [comment]
This needs an RA-side fix, https://github.com/KSP-RO/RealAntennas/issues/38#issuecomment-2294503134.
It then needs a fix here, namely to give ground stations `RACommNetHome`s a ParentBody somehow. That should also fix https://github.com/mockingbirdnest/Skopos/issues/14.

**Comment by eggrobin** [comment]
> It then needs a fix here

It turns out it doesn’t, they have a ParentBody already. Fixed by https://github.com/KSP-RO/RealAntennas/pull/42.
